#configure this for a remote server and a node js server

version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - ./redis-data:/data
    restart: always
  node:
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./node-data:/data
    restart: always
volumes:
  redis-data:
    driver: local
    driver_opts:
      device: /dev/sdb